const ROLES = ["ADMIN", "ANALYST", "VIEWER"];
const SOURCE_TYPES = ["SMI", "NEWS_PORTAL", "TV", "PAPER", "GOVERNMENT", "REGIONAL_MEDIA", "OTHER"];
const AGGREGATION_LEVELS = ["REPUBLICAN", "REGIONAL", "INTERNATIONAL", "UNKNOWN"];
const SOURCE_STATUSES = ["ACTIVE", "NEEDS_REVIEW", "DISABLED"];
const EXTRACTION_STATUSES = ["OK", "WARNING", "ERROR", "NOT_TESTED"];
const CSI_DATA_MODES = ["EXPORT", "API", "MANUAL"];
const COVERAGE_STATUSES = ["OK", "PARTIAL", "FAILED", "CSI_DATA_REQUIRED"];
const MATCH_STATUSES = [
  "MATCHED",
  "MISSING_IN_CSI",
  "DUPLICATE_IN_CSI",
  "TITLE_MISMATCH",
  "URL_MISMATCH",
  "DATE_MISMATCH",
  "LOW_CONFIDENCE",
  "EXTRA_IN_CSI",
];
const ISSUE_TYPES = [
  "EXTRACTION_FAILED",
  "TITLE_SELECTOR_FAILED",
  "LINK_SELECTOR_FAILED",
  "DATE_SELECTOR_FAILED",
  "EMPTY_NEWS_LIST",
  "MISSING_IN_CSI",
  "DUPLICATE_IN_CSI",
  "TITLE_MISMATCH",
  "URL_MISMATCH",
  "DATE_MISMATCH",
  "CSI_DATA_REQUIRED",
  "CSI_API_ERROR",
  "INVALID_EXPORT_FILE",
  "OTHER",
];
const SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const ISSUE_STATUSES = ["NEW", "IN_PROGRESS", "RESOLVED", "IGNORED"];
const TASK_STATUSES = ["TODO", "IN_PROGRESS", "DONE"];
const PRIORITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const KNOWLEDGE_CATEGORIES = [
  "SOURCE_EXTRACTION",
  "CSI_EXPORT",
  "CSI_API",
  "COVERAGE_VALIDATION",
  "SELECTORS",
  "DATA_MATCHING",
  "TROUBLESHOOTING",
  "REPORTING",
];

module.exports = {
  ROLES,
  SOURCE_TYPES,
  AGGREGATION_LEVELS,
  SOURCE_STATUSES,
  EXTRACTION_STATUSES,
  CSI_DATA_MODES,
  COVERAGE_STATUSES,
  MATCH_STATUSES,
  ISSUE_TYPES,
  SEVERITIES,
  ISSUE_STATUSES,
  TASK_STATUSES,
  PRIORITIES,
  KNOWLEDGE_CATEGORIES,
};
